version: '3.9'

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    restart: unless-stopped

  bot:
    build: ./
    restart: unless-stopped
    depends_on:
      - mongo
